// Mocks generated by Mockito 5.4.2 from annotations
// in backend_test_utility/test/websocket_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:backend_services/src/websocket-client/websocket_client.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WebSocketClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketClient extends _i1.Mock implements _i2.WebSocketClient {
  @override
  void connect() => super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  dynamic send(
    String? topic,
    String? json,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #send,
          [
            topic,
            json,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
