name: backend_services
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  dio: ^5.3.0
  dotenv: ^4.1.0
  http: ^1.1.0
  logger: ^1.4.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0
