name: backend_services
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  dart_openai: ^3.0.0
  dotenv: ^4.1.0
  flutter_dotenv: ^5.1.0
  foundation: ^0.0.5
  logger: ^1.4.0
  path: ^1.8.3
  path_provider: ^2.0.15
  stomp_dart_client: ^0.4.4
  uuid: ^3.0.6
  mockito: ^5.4.2
  build_runner: ^2.4.6
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0
