name: Test Secret

on:
    # allow action to be run from github UI
    workflow_dispatch:

jobs:
    build:
        name: Print environment variables
        runs-on: ubuntu-latest
        env:
            TEST_PUBLIC: This is not secret
        
        steps:
            - name: echo secret
              run: |
                echo "My secret is ${{ secrets.TEST_SECRET }}"
                echo "My public property is is ${{ env.TEST_PUBLIC }}"
